"""Add code_files table

Revision ID: 92ae8528c62e
Revises: 001
Create Date: 2025-11-30 11:44:48.390182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ae8528c62e'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_extension', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('uploader_id', sa.String(length=50), nullable=True),
    sa.Column('assignment_id', sa.String(length=50), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=True),
    sa.Column('analysis_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_files_assignment_id'), 'code_files', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_code_files_content_hash'), 'code_files', ['content_hash'], unique=False)
    op.create_index(op.f('ix_code_files_file_id'), 'code_files', ['file_id'], unique=True)
    op.create_index('ix_code_files_language_status', 'code_files', ['language', 'status'], unique=False)
    op.create_index('ix_code_files_uploader_assignment', 'code_files', ['uploader_id', 'assignment_id'], unique=False)
    op.create_index(op.f('ix_code_files_uploader_id'), 'code_files', ['uploader_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_files_uploader_id'), table_name='code_files')
    op.drop_index('ix_code_files_uploader_assignment', table_name='code_files')
    op.drop_index('ix_code_files_language_status', table_name='code_files')
    op.drop_index(op.f('ix_code_files_file_id'), table_name='code_files')
    op.drop_index(op.f('ix_code_files_content_hash'), table_name='code_files')
    op.drop_index(op.f('ix_code_files_assignment_id'), table_name='code_files')
    op.drop_table('code_files')
    # ### end Alembic commands ###

