"""Add feedback_templates and ai_interactions tables

Revision ID: 1691bb2950d3
Revises: 20251214_000000
Create Date: 2025-12-15 21:06:40.941141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1691bb2950d3'
down_revision: Union[str, None] = '20251214_000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 创建 feedback_templates 表
    op.create_table(
        'feedback_templates',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('language', sa.String(length=50), nullable=True),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('severity', sa.String(length=20), nullable=False, server_default='info'),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('variables', sa.JSON(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('usage_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('tone', sa.String(length=20), nullable=True, server_default='neutral'),
        sa.Column('locale', sa.String(length=10), nullable=True, server_default='en'),
        sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_templates_name', 'feedback_templates', ['name'], unique=False)
    op.create_index('ix_feedback_templates_category', 'feedback_templates', ['category'], unique=False)
    op.create_index('ix_feedback_templates_language', 'feedback_templates', ['language'], unique=False)
    op.create_index('ix_feedback_templates_tone', 'feedback_templates', ['tone'], unique=False)
    op.create_index('ix_feedback_templates_locale', 'feedback_templates', ['locale'], unique=False)

    # 创建 ai_interactions 表
    op.create_table(
        'ai_interactions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('session_id', sa.String(length=100), nullable=True),
        sa.Column('interaction_type', sa.String(length=50), nullable=False),
        sa.Column('input_text', sa.Text(), nullable=True),
        sa.Column('output_text', sa.Text(), nullable=True),
        sa.Column('model_used', sa.String(length=100), nullable=True),
        sa.Column('tokens_used', sa.Integer(), nullable=True),
        sa.Column('response_time_ms', sa.Integer(), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_interactions_user_id', 'ai_interactions', ['user_id'], unique=False)
    op.create_index('ix_ai_interactions_session_id', 'ai_interactions', ['session_id'], unique=False)
    op.create_index('ix_ai_interactions_interaction_type', 'ai_interactions', ['interaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_interactions')
    op.drop_table('feedback_templates')
    # ### end Alembic commands ###

