export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as StudentDashboard } from './StudentDashboard';
export { default as SubmitAssignment } from './SubmitAssignment';
export { default as Grades } from './Grades';
export { default as TeacherDashboard } from './TeacherDashboard';
export { default as ManageAssignments } from './ManageAssignments';
export { default as GradingInterface } from './GradingInterface';
export { default as Account } from './Account';
